on:
  workflow_call:
        
jobs:
  gamma-useast:
    uses: ipjohnson-org/templates/.github/workflows/build-stage.yaml@main
    with:
      region: useast
      stage: gamma
  gamma-uswest:
    uses: ipjohnson-org/templates/.github/workflows/build-stage.yaml@main
    needs: gamma-useast
    with:
      region: uswest
      stage: gamma      

