on:
  workflow_call:
    inputs:
      gamma_account_role:
        required: true
        type: string
      prod_account_role:
        required: true
        type: string
        
jobs:
  gamma-useast:
    name: gamma-useast
    uses: ipjohnson-org/templates/.github/workflows/build-stage.yaml@main
    with:
      region: us-east-1
      stage: gamma
      service_account_role: ${{ inputs.gamma_account }}
  gamma-uswest:
    name: gamma-uswest
    uses: ipjohnson-org/templates/.github/workflows/build-stage.yaml@main
    needs: gamma-useast
    with:
      region: us-west-2
      stage: gamma
      service_account_role: ${{ inputs.gamma_account }}
