on:
  workflow_call:
        
jobs:
  trigger-update:
    runs-on: ubuntu-latest
    concurrency:
      group: trigger-update-dependencies
      cancel-in-progress: true
    strategy:
      matrix:
        repo: ['FriendsWithRecipes.Recipes', 'FriendsWithRecipes.IngredientIngest']
        
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_REBUILD: "false"
        PAYLOAD_BRANCH: ${{github.ref}}
      with:
        repository: ipjohnson-org/${{ matrix.repo }}
        event: update_dep
        github_pat: ${{ secrets.UPDATE_DEPENDENCY_PAT }}  
